2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,17 +31,17 @@ jobs:
       - name: Deploy via SSH
         run: |
           ssh -o StrictHostKeyChecking=no \
-           -A \
-              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-            set -e                          # fail on any command error
+            -A \
+            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
+            set -e                            # fail on any command error
             # add GitHub’s host key so ssh won’t complain.
             ssh-keyscan github.com >> ~/.ssh/known_hosts
             # If the directory doesn't exist, clone it:
             if [ ! -d "${{ github.event.repository.name }}" ]; then
-            git clone git@github.com:bhumikapandey1992/${{ github.event.repository.name }}.git
+              git clone git@github.com:bhumikapandey1992/${{ github.event.repository.name }}.git
             fi
             cd ~/${{ github.event.repository.name }}  # enter the cloned folder
-            git pull origin main           # pull the latest changes
-            docker compose up -d --build   # rebuild & restart containers
-            docker image prune -f          # clean up old images
-        EOF:
+            git pull origin main              # pull the latest changes
+            docker compose up -d --build      # rebuild & restart containers
+            docker image prune -f             # clean up old images
+          EOF
